# Generated by Django 6.0.1 on 2026-01-31 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles_published",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publisher_articles",
                to="news.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="articles",
            field=models.ManyToManyField(
                related_name="included_in_newsletters", to="news.article"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters_published",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "EDITOR"},
                related_name="employed_by_publisher_as_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="journalists",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "JOURNALIST"},
                related_name="employed_by_publisher_as_journalist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("READER", "Reader"),
                    ("EDITOR", "Editor"),
                    ("JOURNALIST", "Journalist"),
                ],
                default="READER",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sub_journalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="journalist_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sub_publishers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_readers",
                to="news.publisher"
            ),
        ),
    ]
