# Generated by Django 6.0.1 on 2026-02-03 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_author_alter_article_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role__in': ['JOURNALIST', 'EDITOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='articles_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role__in': ['JOURNALIST', 'EDITOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters_published', to=settings.AUTH_USER_MODEL),
        ),
    ]
