# Generated by Django 6.0.1 on 2026-02-03 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_author_alter_newsletter_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='journalists',
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_publishers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_journalists',
        ),
        migrations.AddField(
            model_name='user',
            name='journalist_followers',
            field=models.ManyToManyField(blank=True, related_name='following_journalists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_readers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('JOURNALIST', 'Journalist'), ('EDITOR', 'Editor')], default='READER', max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
