# Generated by Django 6.0.1 on 2026-02-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_publisher_editors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ManyToManyField(blank=True,
                                                    related_name='newsletters',
                                                    to='news.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.
                                             deletion.CASCADE,
                                             related_name='newsletters',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
