# Generated by Django 6.0.1 on 2026-02-04 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='journalist_followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribed_readers',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
