# Generated by Django 6.0.2 on 2026-02-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_user_journalist_followers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
    ]
